# Generated by Django 3.1.5 on 2021-01-07 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoom_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zoomauth',
            name='auth_token',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
